name: Adrianus Vian Habirowo
email: adrianusvian1@gmail.com
phone: '+6285856564777'
address: Jl. Segitiga No.7A, Joglo, Kembangan, Jakarta Barat
website: https://idjo.cc
git: idjo
linkedin: adr-vian

summary: >
  A passionate DevOps and Infra Engineer. My love for Linux sparked in 2019,
  and since then, it's been my go-to operating system. While my major revolves
  around Cyber Security, my true passion lies in exploring Linux, honing skills
  in Infrastructure and Deployment. I also thrive when immersed in Kubernetes,
  tinkering in my homelab, deploying applications, and engaging in related
  hands-on endeavors.

educations:
  - school: Bina Nusantara University
    degree: Bachelor's degree
    date: 2019 -- 2024
    descriptions: []

workExperiences:
  - company: PT Adira Dinamika Multi Finance Tbk.
    jobTitle: Junior DevOps Engineer
    date: February 2022 -- December 2023
    descriptions:
      - >-
        Creating deployment automation using Jenkins, Docker, Kubernetes, and
        ArgoCD, resulting in significantly faster and more reliable
        deployments.
      - >-
        Orchestrated deployment pipelines that streamlined the release process,
        enhancing efficiency and reducing time-to-market.
      - >-
        Collaborated effectively with developers and operations teams to ensure
        seamless integration of infrastructure and applications.
      - >-
        Standardized deployment and infrastructure configurations to promote
        consistency and reduce configuration drift.
      - >-
        Developed automation tools and scripts to automate manual tasks, saving
        time and effort while minimizing errors.
      - >-
        Proactively monitored and troubleshooted infrastructure issues,
        ensuring high system uptime and availability.
      - >-
        Contributed to measurable improvements in efficiency, scalability, and
        reliability through strategic automation and optimization initiatives.

  - company: PT Adira Dinamika Multi Finance Tbk.
    jobTitle: DevOps Engineer Intern
    date: February 2021 -- February 2022
    descriptions:
      - >-
        Gained valuable hands-on experience in infrastructure management,
        automation practices, and the collaborative DevOps culture.
      - >-
        Developed kubernetes skills and honed problem-solving and communication
        abilities.
      - >-
        Contributed to CI/CD setup and implementation, assisting with pipeline
        configuration and testing.
      - >-
        Proactively monitored systems and documented procedures, ensuring
        operational efficiency and knowledge transfer.
      - >-
        Shadowed experienced engineers and actively participated in team
        discussions, learning best practices and gaining valuable insights.
      - >-
        Successfully develop anchor to help teammates in provisioning
        automation process.

technicalSkills:
  - Linux
  - Golang
  - Python
  - Kubernetes
  - Jenkins
  - Argocd
  - GCP
  - AWS
  - Ali Cloud

certifications:
  - name: AWS Certified Cloud Practitioner
    date: September 15, 2022
  - name: AWS Certified Solutions Architect â€“ Associate
    date: November 01, 2022

trainings:
  - name: AWS Academy Graduate - AWS Academy Cloud Foundations
    date: August 14, 2022
  - name: AWS Academy Graduate - AWS Academy Cloud Architecting
    date: November 01, 2022
